logger:
  level: "info"

app:
  database:
    host: "localhost"
    port: 5033
    name: "name"
    user: "user"
    password: "password"
    migrationspath: "migrations"

api:
  http:
    host: "0.0.0.0"
    port: 8080
  grpc:
    port: 9090
  websocket:
    readbuffersize: 65536
    writebuffersize: 65536
    port: 7070
